name: Rust

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "master", "develop" ]

env:
  CARGO_TERM_COLOR: always



jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      run: cargo fmt --check  --verbose
    - name: Run Clippy
      run: cargo clippy --verbose -- -D warnings

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Move to test package
      run: cd const_typed_builder_test
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
